In [22]:
import numpy as np

In [52]:
li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[16 11 15 15 13]
[ 2  3 14  3 15]


In [4]:
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [24]:
print(a)
a = a + 1
a

[17  2 11  6 12]


array([18,  3, 12,  7, 13])

In [25]:
c = a + b
c

array([24, 17, 25, 14, 24])

In [26]:
d = a - b
d

array([ 12, -11,  -1,   0,   2])

In [27]:
e = a * b
e

array([108,  42, 156,  49, 143])

In [28]:
f = a/b
f

array([3.        , 0.21428571, 0.92307692, 1.        , 1.18181818])

In [29]:
g = a//b
g

array([3, 0, 0, 1, 1])

a = [a,b,c,d]
b = [i,j,k,l]
h = [a^i,b^j,c^k,d^l]

In [53]:
h = a ** b
h

array([              256,              1331, 29192926025390625,
                    3375, 51185893014090757])

In [34]:
a1 = 2
a2 = 3
a3 = a1 ** a2
a3

8

In [13]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.max())
print(a.argmin()) #index of min
print(a.argmax()) #index of max

[11 12 11 20 18]
72
14.4
11
20
0
3


In [ ]:
### Relation operator

In [14]:
print(a)
print(b)

[11 12 11 20 18]
[ 6 14 16  1  9]


In [15]:
a > b

array([ True, False, False,  True,  True])

In [16]:
a < b

array([False,  True,  True, False, False])

In [17]:
a == b

array([False, False, False, False, False])

In [18]:
### logical operator

In [19]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True  True  True]
[ True  True  True  True  True]


In [20]:
print(np.logical_not(a))

[False False False False False]


In [21]:
a[2] = 0
print(np.logical_not(a))

[False False  True False False]


# H.W try for 2d array

In [35]:
li_2d = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
arr_2d = np.array(li_2d)
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [38]:
arr_2d1 = np.random.randint(1,10,(4,5))
arr_2d2 = np.random.randint(10,20,(4,5))
print(arr_2d1)
print()
print(arr_2d2)

[[4 6 4 6 5]
 [3 6 8 9 5]
 [2 3 5 1 3]
 [6 3 6 6 5]]

[[10 18 18 13 12]
 [13 15 12 13 14]
 [10 18 18 15 12]
 [18 17 12 19 11]]


In [39]:
arr_2d3 = arr_2d1 + arr_2d2
arr_2d3

array([[14, 24, 22, 19, 17],
       [16, 21, 20, 22, 19],
       [12, 21, 23, 16, 15],
       [24, 20, 18, 25, 16]])

In [41]:
print(arr_2d1)
print()
print(arr_2d2)
arr_2d4 = arr_2d1 - arr_2d2
arr_2d4

[[4 6 4 6 5]
 [3 6 8 9 5]
 [2 3 5 1 3]
 [6 3 6 6 5]]

[[10 18 18 13 12]
 [13 15 12 13 14]
 [10 18 18 15 12]
 [18 17 12 19 11]]


array([[ -6, -12, -14,  -7,  -7],
       [-10,  -9,  -4,  -4,  -9],
       [ -8, -15, -13, -14,  -9],
       [-12, -14,  -6, -13,  -6]])

In [42]:
print(arr_2d1)
print()
print(arr_2d2)
arr_2d5 = arr_2d1 * arr_2d2
arr_2d5

[[4 6 4 6 5]
 [3 6 8 9 5]
 [2 3 5 1 3]
 [6 3 6 6 5]]

[[10 18 18 13 12]
 [13 15 12 13 14]
 [10 18 18 15 12]
 [18 17 12 19 11]]


array([[ 40, 108,  72,  78,  60],
       [ 39,  90,  96, 117,  70],
       [ 20,  54,  90,  15,  36],
       [108,  51,  72, 114,  55]])

In [43]:
print(arr_2d1)
print()
print(arr_2d2)
arr_2d6 = arr_2d1 / arr_2d2
arr_2d6

[[4 6 4 6 5]
 [3 6 8 9 5]
 [2 3 5 1 3]
 [6 3 6 6 5]]

[[10 18 18 13 12]
 [13 15 12 13 14]
 [10 18 18 15 12]
 [18 17 12 19 11]]


array([[0.4       , 0.33333333, 0.22222222, 0.46153846, 0.41666667],
       [0.23076923, 0.4       , 0.66666667, 0.69230769, 0.35714286],
       [0.2       , 0.16666667, 0.27777778, 0.06666667, 0.25      ],
       [0.33333333, 0.17647059, 0.5       , 0.31578947, 0.45454545]])

In [44]:
print(arr_2d1)
print()
print(arr_2d2)
arr_2d7 = arr_2d1 // arr_2d2
arr_2d7

[[4 6 4 6 5]
 [3 6 8 9 5]
 [2 3 5 1 3]
 [6 3 6 6 5]]

[[10 18 18 13 12]
 [13 15 12 13 14]
 [10 18 18 15 12]
 [18 17 12 19 11]]


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [45]:
print(arr_2d1)
print()
print(arr_2d2)
arr_2d8 = arr_2d1 ** arr_2d2
arr_2d8

[[4 6 4 6 5]
 [3 6 8 9 5]
 [2 3 5 1 3]
 [6 3 6 6 5]]

[[10 18 18 13 12]
 [13 15 12 13 14]
 [10 18 18 15 12]
 [18 17 12 19 11]]


array([[        1048576, 101559956668416,     68719476736,
            13060694016,       244140625],
       [        1594323,    470184984576,     68719476736,
          2541865828329,      6103515625],
       [           1024,       387420489,   3814697265625,
                      1,          531441],
       [101559956668416,       129140163,      2176782336,
        609359740010496,        48828125]])

In [46]:
print(arr_2d1)
print(arr_2d1.sum())
print(arr_2d1.mean())
print(arr_2d1.min())
print(arr_2d1.max())
print(arr_2d1.argmin()) #index of min
print(arr_2d1.argmax()) #index of max

[[4 6 4 6 5]
 [3 6 8 9 5]
 [2 3 5 1 3]
 [6 3 6 6 5]]
96
4.8
1
9
13
8


In [47]:
print(arr_2d1)
print()
print(arr_2d2)

[[4 6 4 6 5]
 [3 6 8 9 5]
 [2 3 5 1 3]
 [6 3 6 6 5]]

[[10 18 18 13 12]
 [13 15 12 13 14]
 [10 18 18 15 12]
 [18 17 12 19 11]]


In [48]:
arr_2d1 < arr_2d2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [49]:
arr_2d1 > arr_2d2

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [50]:
arr_2d1 == arr_2d2

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])