### numpy array is basically collection of pointer which point to four different attribute
1. data -> which refer to the first byte of the array-> means refernce to the first element in the array
2. shape -> which is size of the array
3. dtype -> which represent data type of an element
4. strides -> no. of bytes to skip to get next element

In [18]:
import numpy as np

In [5]:
li = [1,2,3,4,5]
arr = np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [6]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int64
(8,)


### 8, -> means 8 bytes need to be skip inordered to move from one elelemnt to the next element -> means 1 integer taking 8 byte 

In [9]:
print(li[3])
print(arr[3])
print(li[2:4])
#slicing
print(arr[2:4])

4
4
[3, 4]
[3 4]


In [19]:
li_2d = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d = np.array(li_2d)

print(li_2d)
print()
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [7]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int64
(32, 8)


### 32, -> represt no. of byte to be skip to get next row
### 8 -> represt if we want A element to skip in the same row then we required 8 byte

In [20]:
print(arr_2d)
print(li_2d[2][1])
print(arr_2d[2][1])
print(arr_2d[2,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
10
10
10


# constant row, vari colomn

In [11]:
print(li_2d[1][:3])
print(arr_2d[1][:3])
print(arr_2d[1,:3])

[5, 6, 7]
[5 6 7]
[5 6 7]


In [12]:
print(li_2d[:3][3])

IndexError: list index out of range

In [22]:
print(arr_2d)
print()
print(li_2d[0:3][2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[9, 10, 11, 12]


In [14]:
x = li_2d[0:3]
print(x)
y = x[2]
print(y)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


# constant column, vari row

In [24]:
print(arr_2d)
print()
print(arr_2d[0:3, 2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[ 3  7 11]


In [16]:
print(arr_2d[2:4,1:3])

[[10 11]
 [14 15]]


In [17]:
# not workoing for list
print(li_2d[2:4][1:3])

[[13, 14, 15, 16]]
