In [23]:
import numpy as np

## numpy.arrange
### numpy.arnage([start],stop,[step],dtype=None)

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a = np.arange(2,10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a = np.arange(2,10,2)
a

array([2, 4, 6, 8])

## numpy.linspace
### numpy.linspace(start,num=50,endpoint=True,retstep=False,dtype=None,axis=0)

In [2]:
b = np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [3]:
b = np.linspace(2,10)
b
print(b[1]-b[0])
print(b[3]-b[2])

0.16326530612244916
0.16326530612244916


### value 2 and 10 ka bitch me hoga or 5 size ka array hoga

In [4]:
b = np.linspace(2,10,5)
b

array([ 2.,  4.,  6.,  8., 10.])

In [5]:
b = np.linspace(2,10,5,dtype=int)
b

array([ 2,  4,  6,  8, 10])

In [6]:
b = np.linspace(2,10,5,dtype=int,endpoint = False)
b

array([2, 3, 5, 6, 8])

In [21]:
b = np.linspace(2,3,4,dtype=int)
b

array([2, 2, 2, 3])

### np.arange() -> i have a control in steps value\
### np.linspace() -> i have control in no. of sample i want to generate

### np.identity() -> n*n is square matrix

In [7]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.eye() -> n*m matrix

In [8]:
b = np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
b = np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### np.random.rand() -> random generated value from 0 to 1

In [10]:
b = np.random.rand(3)
b

array([0.19732186, 0.74042128, 0.40010287])

In [27]:
b = np.random.rand(2,3)
b

array([[0.24816506, 0.27225415, 0.22323397],
       [0.64723253, 0.2370652 , 0.20993859]])

In [28]:
b = np.random.rand(3,2)
b

array([[0.94636704, 0.4940269 ],
       [0.92983736, 0.48538358],
       [0.29117263, 0.89059734]])

### we are explicitly changing the range using multiply
 here range he 1 to 10

In [12]:
b = np.random.rand(10)*10
b

array([1.63136823, 8.12583188, 2.47917264, 7.43014882, 3.67248679,
       2.76708583, 9.88035178, 0.76252184, 0.95951233, 2.28692767])

### np.random.randint() -> generate int random value

In [25]:
b = np.random.randint(3)
b

1

In [14]:
b = np.random.randint(3)*10
b

20

In [29]:
b = np.random.randint(3,size=3)
b

array([2, 2, 2])

In [30]:
b = np.random.randint(2,size=3)
b

array([1, 1, 1])

In [31]:
b = np.random.randint(4,size=(3,4))
b

array([[3, 0, 3, 3],
       [2, 3, 0, 3],
       [2, 1, 1, 1]])

In [41]:
b = np.random.randint(1,[3,4,10])
b

array([1, 1, 6])

In [46]:
b = np.random.randint([1,5,7],10)
b

array([8, 8, 7])