### earlyer we learn same type of dimension we work a+b,a-b,a*b
### but 
### what if we work for different dimension then we use
## BRoadcasting -> which tells how numpy will treat the unequal size of the array

In [10]:
import numpy as np

In [2]:
x = np.random.randint(1,10,(3, 3))
y = np.random.randint(1,10,(3, 3))
print(x)
print(y)

[[8 3 7]
 [9 7 9]
 [1 2 2]]
[[5 9 4]
 [4 5 7]
 [1 4 6]]


In [3]:
ans = x - y
print(ans)

[[ 3 -6  3]
 [ 5  2  2]
 [ 0 -2 -4]]


In [4]:
x = np.random.randint(1,10,(3, 3))
y = np.random.randint(1,10,(3))
print(x)
print(y)

[[3 4 4]
 [1 4 7]
 [2 9 2]]
[6 6 8]


In [5]:
ans = x - y
print(ans)

[[-3 -2 -4]
 [-5 -2 -1]
 [-4  3 -6]]


In [11]:
x = np.random.randint(1,10,(2, 3))
y = np.random.randint(1,10,(3,2))
print(x)
print(y)

[[2 6 5]
 [5 9 5]]
[[7 1]
 [5 6]
 [8 2]]


In [7]:
ans = x - y
print(ans)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

### we are using np.transpose() -> to make compatiable inorder to perform element by element comparision

In [12]:
y = np.transpose(y)
print(y)
ans = x - y
print(ans)

[[7 5 8]
 [1 6 2]]
[[-5  1 -3]
 [ 4  3  3]]


In [13]:
x = np.random.randint(1,10,(2, 3))
y = np.random.randint(1,10,(3,1))
print(x)
print(y)

[[3 1 5]
 [6 8 7]]
[[4]
 [6]
 [2]]


In [14]:
ans = x - y
print(ans)

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [15]:
y = np.transpose(y)
print(y)
ans = x - y
print(ans)

[[4 6 2]]
[[-1 -5  3]
 [ 2  2  5]]


# H.W resize() and reshape()

In [21]:
a = np.random.randint(1,10,(2,3))
b = np.random.randint(1,10,(3,2))
print(a)
print(b)

[[5 6 5]
 [3 2 2]]
[[4 7]
 [3 1]
 [6 3]]


In [18]:
print(a)
a = np.resize(a,(3,2))
print(a)

[[3 8 8]
 [3 4 6]]
[[3 8]
 [8 3]
 [4 6]]


In [19]:
print(a)
a = np.resize(a,(3,1))
print(a)

[[3 8]
 [8 3]
 [4 6]]
[[3]
 [8]
 [8]]


In [22]:
print(a)
a = np.resize(a,(1,4))
print(a)

[[5 6 5]
 [3 2 2]]
[[5 6 5 3]]


In [26]:
c = np.arange(6)
c

array([0, 1, 2, 3, 4, 5])

In [24]:
c = np.arange(6).reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
c = np.arange(6).reshape(3,2)
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [29]:
c = np.reshape(c,(2,3))
c

array([[0, 1, 2],
       [3, 4, 5]])