In [2]:
import numpy as np

a = [1,2,3,4]
b = np.array(a)
print(b)
print(type(b))

[1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
a = [1,2,3,4,'22','a',9.98]
b = np.array(a)
print(b)
print(type(b))

['1' '2' '3' '4' '22' 'a' '9.98']
<class 'numpy.ndarray'>


## dtype -> inorder to set user data type

In [3]:
a = [1,2,3,4,'22','a',9.98]
b = np.array(a, dtype = int)
print(b)
print(type(b))

ValueError: invalid literal for int() with base 10: 'a'

In [4]:
a = [1,2,3,4,'22',9.98]
b = np.array(a, dtype = int)
print(b)
print(type(b))

[ 1  2  3  4 22  9]
<class 'numpy.ndarray'>


In [5]:
a = [1,2,3,4,'22',9.98]
b = np.array(a, dtype = float)
print(b)
print(type(b))

[ 1.    2.    3.    4.   22.    9.98]
<class 'numpy.ndarray'>


In [6]:
a = [1,2,3,4,'22',9.98]
b = np.array(a, dtype = str)
print(b)
print(type(b))

['1' '2' '3' '4' '22' '9.98']
<class 'numpy.ndarray'>


In [3]:
c = np.ones(3)
print(c)

[1. 1. 1.]


In [7]:
c = np.ones(3, dtype=int)
print(c)

[1 1 1]


In [8]:
c = np.ones((2,3),dtype=int)
print(c)

[[1 1 1]
 [1 1 1]]


In [5]:
c = np.zeros(3)
print(c)

[0. 0. 0.]


In [6]:
c = np.zeros(3, dtype=int)
print(c)

[0 0 0]


In [9]:
c = np.zeros((3,4),dtype=int)
print(c)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [10]:
d = np.full(3,6)
print(d)

[6 6 6]


In [11]:
d = np.full(3,6, dtype=str)
print(d)

['6' '6' '6']


In [12]:
d = np.full((3,4),6, dtype=str)
print(d)

[['6' '6' '6' '6']
 ['6' '6' '6' '6']
 ['6' '6' '6' '6']]


In [14]:
e = np.empty(3)
print(e)

[3.e-323 3.e-323 3.e-323]


In [15]:
e = np.empty((2,3))
print(e)

[[4.65737397e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [5]:
e = np.empty([2,2])
print(e)

[[4.64902919e-310 0.00000000e+000]
 [4.64835975e-310 4.64835975e-310]]


In [6]:
e = np.empty([2,3])
print(e)

[[4.6490292e-310 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]


In [7]:
e = np.empty([3])
print(e)

[4.64902919e-310 4.64835975e-310 4.64835975e-310]
