In [1]:
import numpy as np

In [9]:
arr_age = np.arange(1,21,dtype=int)
arr_height = np.random.randint(1,200,20)
print(arr_height)
print(arr_age)

[132  97 182 175  35  57  75 104 194 189  99 115  45 127 121  62 148 159
 147  53]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [10]:
arr_ele = arr_height>155
arr_ele

array([False, False,  True,  True, False, False, False, False,  True,
        True, False, False, False, False, False, False, False,  True,
       False, False])

In [11]:
output = arr_age[arr_ele]
output

array([ 3,  4,  9, 10, 18])