###  Given a 2D integer array size (4, 5) with name input_?
Print elements of highlighted matrix

In [1]:
import numpy as np

In [3]:
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [12]:
arr_ele1 = arr_2d[2][:3]
arr_ele1

array([11, 12, 13])

In [13]:
arr_ele1 = arr_2d[2,:3]
arr_ele1

array([11, 12, 13])

In [11]:
arr_ele2 = arr_2d[1:4,3]
arr_ele2

array([ 9, 14, 19])

In [14]:
arr_ele3 = arr_2d[2:4,:5]
arr_ele3

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [15]:
arr_ele4 = arr_2d[1:3,1:3]
arr_ele4

array([[ 7,  8],
       [12, 13]])