In [32]:
import numpy as np

In [53]:
li = [[21,20,19,18,17],[16,15,14,13,12],[11,10,9,8,7],[6,5,4,3,2]]
arr = np.array(li)
arr

array([[21, 20, 19, 18, 17],
       [16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2]])

In [54]:
sorted_array = arr[arr[:, 1].argsort()]
print(sorted_array)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


In [42]:
arr_ele = arr[:4,0]
arr_ele = arr_ele[-1:-5:-1]
arr_ele

array([ 6, 11, 16, 21])

In [84]:
# print(arr)
i=-1
j=-5
k=-1
while(i != j):
    arr = arr[i:j:k]
    i-=1
    j+=1
arr

array([[16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7]])

In [75]:
i=-1
j=-5
k=-1
arr = arr[i:j:k]
arr

array([[ 6,  5,  4,  3,  2],
       [11, 10,  9,  8,  7],
       [16, 15, 14, 13, 12],
       [21, 20, 19, 18, 17]])

In [88]:
arr[-4]

array([21, 20, 19, 18, 17])

In [4]:
arr = np.array(li)
arr

array([ 2, 23,  1,  4, 66,  1])

In [5]:
arr = arr.dec()
arr

AttributeError: 'numpy.ndarray' object has no attribute 'dec'

In [7]:
arr.array.sort()
arr

AttributeError: 'numpy.ndarray' object has no attribute 'array'

In [26]:
li = [2,23,1,4,66,1]
li

[2, 23, 1, 4, 66, 1]

In [28]:
li[1:5:1]

[23, 1, 4, 66]

In [38]:
li[-1:-7:-1]

[1, 66, 4, 1, 23, 2]

In [32]:
li[-1]

1

In [34]:
li[-6]

2

In [46]:
arr = np.array([[1,12,3],[14,5,6],[7,8,19]])
arr

array([[ 1, 12,  3],
       [14,  5,  6],
       [ 7,  8, 19]])

In [47]:
#sort the first column array in inc oreder
index = np.argsort(arr[:, 0])
arr[index]

array([[ 1, 12,  3],
       [ 7,  8, 19],
       [14,  5,  6]])

In [25]:
#sort the second column array in inc oreder
index = np.argsort(arr[:, 1])
arr[index]

array([[14,  5,  6],
       [ 7,  8, 19],
       [ 1, 12,  3]])

In [24]:
#sort the third column array in inc oreder
index = np.argsort(arr[:, 2])
arr[index]

array([[ 1, 12,  3],
       [14,  5,  6],
       [ 7,  8, 19]])

In [48]:
print(arr[index[::-1]])

[[14  5  6]
 [ 7  8 19]
 [ 1 12  3]]


In [43]:
index = np.argsort(arr[:, :3], axis=1)
d = arr[index]
d

array([[[11, 10,  9,  8,  7],
        [16, 15, 14, 13, 12],
        [21, 20, 19, 18, 17]],

       [[11, 10,  9,  8,  7],
        [16, 15, 14, 13, 12],
        [21, 20, 19, 18, 17]],

       [[11, 10,  9,  8,  7],
        [16, 15, 14, 13, 12],
        [21, 20, 19, 18, 17]],

       [[11, 10,  9,  8,  7],
        [16, 15, 14, 13, 12],
        [21, 20, 19, 18, 17]]])

In [36]:
b = np.copy(arr)
b

array([[21, 20, 19, 18, 17],
       [16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2]])

In [50]:
b = b[b[:, 1]].argsort(kind='d')
b

IndexError: index 20 is out of bounds for axis 0 with size 4

In [44]:
c = np.copy(d)
c

array([[[11, 10,  9,  8,  7],
        [16, 15, 14, 13, 12],
        [21, 20, 19, 18, 17]],

       [[11, 10,  9,  8,  7],
        [16, 15, 14, 13, 12],
        [21, 20, 19, 18, 17]],

       [[11, 10,  9,  8,  7],
        [16, 15, 14, 13, 12],
        [21, 20, 19, 18, 17]],

       [[11, 10,  9,  8,  7],
        [16, 15, 14, 13, 12],
        [21, 20, 19, 18, 17]]])

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]
