In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,30,(5,6))
print(a)

[[20 20 14  1  6 29]
 [20 13 13 11  5 20]
 [ 7 12 25 26 12  8]
 [ 9 22 13 12 29 23]
 [10  9  8  4  2 13]]


In [3]:
bool_arr = a>20
print(bool_arr)

[[False False False False False  True]
 [False False False False False False]
 [False False  True  True False False]
 [False  True False False  True  True]
 [False False False False False False]]


In [4]:
ans = a[bool_arr]
ans

array([29, 25, 26, 22, 29, 23])

In [5]:
b = a
print(b)

[[20 20 14  1  6 29]
 [20 13 13 11  5 20]
 [ 7 12 25 26 12  8]
 [ 9 22 13 12 29 23]
 [10  9  8  4  2 13]]


In [ ]:
# we can modify only if the dimension of a and b both are same

In [6]:
b[bool_arr] = 100
print(b)

[[ 20  20  14   1   6 100]
 [ 20  13  13  11   5  20]
 [  7  12 100 100  12   8]
 [  9 100  13  12 100 100]
 [ 10   9   8   4   2  13]]


In [7]:
c = np.random.randint(1,10,(2,2))
print(c)

[[3 9]
 [4 4]]


In [9]:
c_bool = np.array([[True,False],[False,True],[True,True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [10]:
print(c[c_bool])

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 3

In [11]:
print(b)

[[ 20  20  14   1   6 100]
 [ 20  13  13  11   5  20]
 [  7  12 100 100  12   8]
 [  9 100  13  12 100 100]
 [ 10   9   8   4   2  13]]


In [12]:
bool_arr = b[:, 3] == 100
print(bool_arr)

[False False  True False False]


In [13]:
b[bool_arr, 3] = 99
print(b)

[[ 20  20  14   1   6 100]
 [ 20  13  13  11   5  20]
 [  7  12 100  99  12   8]
 [  9 100  13  12 100 100]
 [ 10   9   8   4   2  13]]
