In [27]:
import csv
import numpy as np
import pandas as pd

# please solve this question using numpy

In [ ]:
# my method but using panda

In [29]:
with open('terrorismData.csv') as file_obj:
    file_data = csv.DictReader(file_obj, skipinitialspace=True)
    
    data = pd.read_csv('terrorismData.csv')

    filtered_data = data[ (data['Year'] == 2010) & (data['Month']==1) & ((data['Day']>0) & (data['Day']<32))]
    
filtered_data 
print(len(filtered_data))

271


In [ ]:
li = [x for ]

In [1]:
li = [int(x) for x in input().split()]
li

1 2 3 4


[1, 2, 3, 4]

In [2]:
li[0]

1

In [2]:
li[0] = 100

NameError: name 'li' is not defined

In [13]:
a=11
b=12
c1  = a>10
c2 = b<20
r1 = c1 and c2
r2 = c1 & c2
print(r1)
print(r2)

True
True


In [24]:
with open('terrorismData.csv') as file_obj:
    file_data = csv.DictReader(file_obj, skipinitialspace=True)
    year = []
    month = []
    day = []
    for row in file_data:
        year.append(row['Year'])
        month.append(row['Month'])
        day.append([row['Day']])
        
    np_year = np.array(year,int)
    np_month = np.array(month,int)
    np_day = np.array(day,int)
    
    valid_day = np_day[(np_day>=1) & (np_day<=31)]
    valid_month = np_month== 1
    vaild_year = np_year==2010
    
    np_year_month_day = (valid_day) & (valid_month) & (valid_year)

print(valid_day)
print(np_year_month_day)

ValueError: operands could not be broadcast together with shapes (180800,) (181691,) 

In [15]:
import pandas as pd

In [20]:
import pandas as pd
import numpy as np

# Read the CSV file into a pandas DataFrame
data = pd.read_csv("terrorismData.csv")

# Convert the 'iyear', 'imonth', and 'iday' columns to datetime format
data['date'] = pd.to_datetime(data[['Year', 'Month', 'Day']], errors='coerce')

# Filter rows between 1 Jan 2010 and 31 Jan 2010
filtered_data = data[(data['date'] >= '2010-01-01') & (data['date'] <= '2010-01-31')]

# Get the count of attacks
number_of_attacks = np.sum(filtered_data['date'].notnull())

# Print the count of attacks as an integer value
print(int(number_of_attacks))
print(len(filtered_data))

271
271


In [21]:
x = np.random.randint(1,10,(3,1))
y = np.random.randint(1,10,(3,3))
print(x)
print()
print(y)

[[6]
 [5]
 [6]]

[[8 6 3]
 [6 7 7]
 [4 6 1]]


In [22]:
ans = x+y
print(ans)

[[14 12  9]
 [11 12 12]
 [10 12  7]]
