In [1]:
import numpy as np

In [2]:
a = np.array(['t','b','r','d','e','f','z','a'])
b = np.random.randint(1,20,8)

print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[12 18 19  8  6 19 15  3]


In [3]:
print(b>10)

[ True  True  True False False  True  True False]


In [ ]:
# M-1

In [4]:
bool_arr = b>10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)

[ True  True  True False False  True  True False]
[12 18 19 19 15]


In [5]:
# M-2

In [6]:
new_arr = b[b>10]
new_arr

array([12, 18, 19, 19, 15])

In [7]:
# & <- logical and

In [8]:
new_arr = b[(b>10) & (b<18)]
new_arr

array([12, 15])

In [9]:
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[12 18 19  8  6 19 15  3]


In [10]:
c = b
c

array([12, 18, 19,  8,  6, 19, 15,  3])

In [11]:
c[:3] = 19
print(c)
c[c>15] = 100
c

[19 19 19  8  6 19 15  3]


array([100, 100, 100,   8,   6, 100,  15,   3])

# np.where() -> we get the indexes for which for condition is satisified

In [12]:
print(b[b == 100])

[100 100 100 100]


In [13]:
ind = np.where(b==100)
ind

(array([0, 1, 2, 5]),)

In [14]:
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[100 100 100   8   6 100  15   3]


In [15]:
ind  = np.where(b == 100)
print(ind)
print(a[ind])

(array([0, 1, 2, 5]),)
['t' 'b' 'r' 'f']
